import { existsSync } from 'node:fs';
import type { Command } from 'commander';
import { execa } from 'execa';
import { getApplybotPaths } from '../shared/appPaths.js';
import { validateConfigFile } from '../config/schema.js';
import { resolveChromePath } from '../stages/apply/chrome.js';

async function checkBinary(name: string, args: string[] = ['--version']) {
  try {
    const result = await execa(name, args, { reject: false });
    return {
      present: result.exitCode === 0,
      details: result.stdout?.split(/\r?\n/)[0] ?? result.stderr?.split(/\r?\n/)[0] ?? 'available'
    };
  } catch (error) {
    return {
      present: false,
      details: error instanceof Error ? error.message : String(error)
    };
  }
}

export function registerDoctorCommand(program: Command) {
  program
    .command('doctor')
    .description('Check environment diagnostics for applybot')
    .action(async () => {
      const paths = getApplybotPaths();

      const [claude, codex, node, npx] = await Promise.all([
        checkBinary('claude'),
        checkBinary('codex'),
        checkBinary('node'),
        checkBinary('npx')
      ]);

      let chromePath = '';
      let chromeOk = false;
      try {
        chromePath = await resolveChromePath();
        chromeOk = true;
      } catch (error) {
        chromePath = error instanceof Error ? error.message : String(error);
      }

      const configExists = existsSync(paths.configPath);
      const configValidation = configExists ? await validateConfigFile(paths.configPath) : null;

      const rows = [
        { check: 'claude binary', ok: claude.present, details: claude.details },
        { check: 'codex binary', ok: codex.present, details: codex.details },
        { check: 'chrome present', ok: chromeOk, details: chromePath },
        { check: 'node present', ok: node.present, details: node.details },
        { check: 'npx present', ok: npx.present, details: npx.details },
        {
          check: 'config path',
          ok: configExists,
          details: configExists ? paths.configPath : `missing (${paths.configPath})`
        },
        {
          check: 'config validation',
          ok: configValidation ? configValidation.success : false,
          details: configValidation?.success
            ? 'valid'
            : configValidation
              ? configValidation.error.issues.map((issue) => `${issue.path.join('.')}: ${issue.message}`).join('; ')
              : 'config missing'
        }
      ];

      console.table(rows);
      console.log('Codex MCP trust guidance:');
      console.log('- If codex blocks MCP config, run: codex trust .');
      console.log('- Ensure worker .codex/config.toml is generated by applybot apply.');

      if (!claude.present) {
        console.log('Remediation: install Claude Code CLI and ensure `claude` is on PATH.');
      }
      if (!codex.present) {
        console.log('Remediation: install Codex CLI and ensure `codex` is on PATH.');
      }
      if (!chromeOk) {
        console.log('Remediation: install Chrome/Edge or set CHROME_PATH.');
      }
      if (!configExists) {
        console.log('Remediation: run `applybot init`.');
      }
    });
}
